config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :follows

  root to: "pages#home"

  resources :lists, shallow: true do
    resources :gifts
  end

  # LO ANTERIOR, ES LO MISMO QUE DECIR: (Shallow, nestea solo con new y create)
  # resources :lists do
  #   resources :gifts, only: %i[new create]
  # end

  resources :gifts, only: %i[show index edit update destroy] do

    resources :comments, only: %i[create]
  end

  # reservar regalo
  post '/gift/:id/reservar', to: "gifts#reserve", as: "reserve_gift"
  post '/gift/:id/desreservar', to: "gifts#unreserve", as: "unreserve_gift"

  resources :comments, only: %i[update destroy]
  resources :users, only: %i[index show]

  # Followers model
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/followers', to: "users#followers", as: "user_followers"
  get '/users/:id/followees', to: "users#followees", as: "user_followees"

  get '/search', to: "pages#searches", as: "search"

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :gifts, dependent: :destroy

  validates :title, :privacy, presence: true
  validates :title, length: { maximum: 30 }
  validates :description, length: { maximum: 280 }
  validates :privacy, inclusion: { in: %w[pública privada] }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_user, only: %i[new create edit update destroy]
  before_action :set_list, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # @lists = List.all
    @list = List.new
    @lists = policy_scope(List)
    @gift = Gift.all
  end

  def new
    @list = List.new
    authorize @list
  end

  def show
    authorize @list
  end

  def create
    @list = List.new(list_params)
    @list.user = @user
    if @list.save
      redirect_to lists_path
    else
      @lists = policy_scope(List)
      render :index, status: :unprocessable_entity
    end
    authorize @list
  end

  def edit
    authorize @list
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
    authorize @list
  end

  def destroy
    @list.destroy
    redirect_to lists_path
    authorize @list
  end

  private

  def list_params
    params.require(:list).permit(:title, :description, :privacy)
  end

  def set_list
    @list = List.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/views/lists/_list_card.html.erb
<div  class="flip-card card-category list-card py-4 mb-3 d-flex flex-column">
  <%= '<span class="new-badge badge bg-success small">new</span>'.html_safe if list.created_at >= (Date.today -7)  %>
  <div class="flip-card-inner" tab-index="0">
    <div class="flip-card-front">
      <%= link_to list_path(list) do %>
        <div>
          <h2><%= list.title %></h2>
          <p>De: <%= list.user.user_name %></p>
        </div>
        <div class="d-flex flex-column justify-content-between align-items-center">
          <div class="m-2">
            <i class="fa-sharp fa-solid fa-gift"></i>
            <span class="badge bg-primary rounded-pill m-0"><%= list.gifts.count %></span>
          </div>
        </div>
      <% end %>
    </div>
    <div class="flip-card-back">
      <%= link_to list_path(list) do %>
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-pause="false" data-bs-ride="carousel" data-bs-interval="100">
        <div class="carousel-inner flip-list-card">
          <% list.gifts.each_with_index do |gift, index| %>
            <% if gift.photo.attached? %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <%= cl_image_tag gift.photo&.key %>
              </div>
            <% else %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <%= image_tag "random-gift.jpg" %>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Ver Más", list_path(list), class:"btn btn-primary" %>
</div>

app/views/lists/_list_new_form.html.erb
  <div class="">
    <%= simple_form_for @list, html: { class: "d-flex justify-content-between form-list align-items-center"} do |f| %>
      <%= f.input :title, label: false,
      placeholder: "Titulo", wrapper_html: { class: 'form-item' }  %>
      <%= f.input :description, label: false,
      placeholder: "Descripcion de la lista", wrapper_html: { class: 'form-item' } %>
      <%= f.input :privacy, label:false, collection: ['pública', 'privada'], include_blank: false, wrapper_html: { class: 'form-item' }  %>
      <%= f.button :submit, "+", class: "btn btn-primary" %>

    <%= f.error_notification %>
    <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
    <% end %>
  </div>

app/views/lists/edit.html.erb
<div class="container my-3 ">
  <div class="my-3 list-edit-container">

      <%= simple_form_for @list do |f| %>
      <div class="row ">
        <div class="col-6 px-5 fondo" >
          <div class="foto d-flex flex-column align-items-center pt-5">
            <%= image_tag "backgrounds/edit-list2.jpg" %>
          </div>
        </div>
        <div class="col-6 px-5 ">
          <h2 class="text-uppercase mb-4 text-center pt-4">Edita tu Lista</h2>
          <div class=" pt-3">
            <%= f.input :title, label: "Titulo", wrapper_html: { class: '' } %>
            <%= f.input :description, label: "Descripcion", wrapper_html: { class: '' }  %>
            <%= f.input :privacy, collection: ["pública", "privada" ], wrapper_html: { class: '' }  %>
            </div>
            <div class="form-actions d-flex flex-column align-items-center justify-content-around">
              <%= f.button :submit, "Editar Lista", class: "btn btn-primary my-3"  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row" data-controller="form-index">
    <div class="d-flex align-items-center justify-content-center my-4">
      <%= link_to "Crear Lista Nueva", new_list_path, class: "btn btn-primary", data: {action: "click->form-index#showCreate"} if policy(List).new? %>
    </div>
    <div class="d-none" data-form-index-target="form">
      <%= render 'list_new_form' %>
    </div>
  </div>

  <div class="flip-cards-grid">
    <div class="list-group my-4 flip-cards-grid">
        <%# Faltaria filtrar privacidad %>
        <% if params[:user].present? %>
          <% @lists.where(user_id: params[:user]).each do |list| %>
            <%= render 'list_card', list: list %>
          <% end %>
        <% else %>
          <% @lists.where(privacy: "pública").each do |list| %>
            <%= render 'list_card', list: list if list.gifts.present? %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div style="font-size: 1.8em;">
  <div class="module-border-wrap" >
    <div class="module">
      <div class="container text-uppercase justify-content-between  d-flex align-items-center my-0 py-0">
        <h1 style="">Crear una Nueva Lista</h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%= render 'list_new_form' %>
</div>

app/views/lists/show.html.erb
<div id="list-show">
  <div class="top-section">
    <div class="container">
      <div class="list-header text-uppercase justify-content-evenly d-flex align-items-center my-4">
        <div class="d-flex flex-column align-items-center p-4 user-div">
          <% if @list.user.photo.attached? %>
              <%= cl_image_tag @list.user.photo.key, class: "avatar dropdown-toggle align-items-center", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "random-user.png", class: "avatar dropdown-toggle align-items-center", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <p><a href="<%= user_path(@list.user)%>"><%= @list.user.user_name %></a></p>
          <p class="text-center small"><i class="fa-solid fa-cake-candles"></i> <%= @list.user.birth_date %></p>
          <div class="dflex">
            <%= link_to '<i class="fa-solid fa-circle-plus"></i> <i class="fa-sharp fa-solid fa-gift"></i>'.html_safe, new_list_gift_path(@list, @gift), class: "btn btn-primary" if @list.user == @current_user %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, list_path(@list), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} if policy(@list).destroy?  %>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_list_path(@list), class:"btn btn-primary" if policy(@list).edit? %>
          </div>
        </div>
        <div class="d-flex flex-column align-items-center p-4">
          <h1 class="text-uppercase "><%= @list.title %></h1>
            <a class="whatsapp-share btn m-2" href="https://wa.me/?text=Mira mi lista de regalos en Galo: http://localhost:3000<%= list_path(@list) %>" target="_blank"><i class="fa-brands fa-square-whatsapp"></i> Compartir </a>
          <p class="text-center small"><%= @list.description %></p>
          <div class="m-1">
            <i class="fa-sharp fa-solid fa-gift"></i>
            <span class="badge bg-primary rounded-pill m-0"><%= @list.gifts.count %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-section">
    <div class="container">
      <div class="cards my-4">
        <% @list.gifts.all.each do |gift| %>
          <%= render 'gifts/gift_card', gift: gift %>
        <% end %>
      </div>
    </div>
  </div>
</div>