config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :follows

  root to: "pages#home"

  resources :lists, shallow: true do
    resources :gifts
  end

  # LO ANTERIOR, ES LO MISMO QUE DECIR: (Shallow, nestea solo con new y create)
  # resources :lists do
  #   resources :gifts, only: %i[new create]
  # end

  resources :gifts, only: %i[show index edit update destroy] do

    resources :comments, only: %i[create]
  end

  # reservar regalo
  post '/gift/:id/reservar', to: "gifts#reserve", as: "reserve_gift"
  post '/gift/:id/desreservar', to: "gifts#unreserve", as: "unreserve_gift"

  resources :comments, only: %i[update destroy]
  resources :users, only: %i[index show]

  # Followers model
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/followers', to: "users#followers", as: "user_followers"
  get '/users/:id/followees', to: "users#followees", as: "user_followees"

  get '/search', to: "pages#searches", as: "search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :lists
  has_many :comments
  has_many :gifts, through: :lists

  # followers relations
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  validates :user_name, uniqueness: true, presence: true
  validates :user_name, length: { in: 6..30 }

  include PgSearch::Model
  multisearchable against: %i[user_name first_name last_name]

  after_create :create_default_list

  private

  def create_default_list
    List.create(title: "Lista Principal", description: "Mi Lista Principal", privacy: "pública", user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @lists = List.all
    @users = User.all
    # @lists = policy_scope(List)
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    @lists = List.all
    @gifts = @user.gifts
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    authorize @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    authorize @user
    redirect_back(fallback_location: user_path(@user))
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render "index"
    authorize current_user
  end

  def followees
    @user = User.find(params[:id])
    @users = @user.followees
    render "index"
    authorize current_user
  end

end

app/views/users/_search_user.html.erb
<div class="col-12">
  <figure class="snip1336">
    <%= cl_image_tag element.searchable.photo.key if element.searchable.photo.attached? %>
    <figcaption>
      <h2><%= element.searchable.first_name %> <%= element.searchable.last_name %><span><%= element.searchable.user_name %></span></h2>
      <p class="metrics-links"><%= element.searchable.gifts.count %> Regalos <%= element.searchable.lists.count %> Listas <%= link_to "#{element.searchable.followers.count} Seguidores", user_followers_path(element) %> <%= link_to "#{element.searchable.followees.count} Seguidos", user_followees_path(element) %></p>
      <p><i class="fa-solid fa-map-location-dot"></i> <%= element.searchable.address %></p>
      <p><i class="fa-solid fa-cake-candles"></i> <%= element.searchable.birth_date %></p>
      <section class="follow-links">
        <% if element.searchable.id == current_user.id %>
            <%= button_to "Logout", '/logout', method: :post %>
        <% elsif current_user.followees.include?(element.searchable) %>
            <h5><%= button_to "Unfollow", unfollow_user_path(element.searchable), method: "POST" %></h5>
        <% else %>
            <h5><%= button_to "Follow", follow_user_path(element.searchable), method: "POST"  %></h5>
        <% end%>
      </section>
      <a href="<%= user_path(element.searchable)%>" class="follow">Ir al Perfil</a>
    </figcaption>
  </figure>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= '<h2 class="text-center m-5 p-5">Todavia no tenes amigos, navega por las listas y regalos y segui a quien quieras</h2>'.html_safe if @users.empty? %>
  <div class="cards">
    <% @users.each do |user| %>
      <div>
        <figure class="snip1336">
          <% if user.photo.attached? %>
            <%= cl_image_tag user.photo.key %>
          <% else %>
            <%= image_tag "random-gift.jpg", crop: :fill %>
          <% end %>
          <figcaption>
            <h2><%= user.first_name %> <%= user.last_name %><span><%= user.user_name %></span></h2>
            <p class="metrics-links"><%= user.gifts.count %> Regalos <%= user.lists.count %> Listas <%= link_to "#{user.followers.count} Seguidores", user_followers_path(user) %> <%= link_to "#{user.followees.count} Seguidos", user_followees_path(user) %></p>
            <p><i class="fa-solid fa-map-location-dot"></i> <%= user.address %></p>
            <p><i class="fa-solid fa-cake-candles"></i> <%= user.birth_date %></p>
            <section class="follow-links">
              <% if user.id == current_user.id %>
                <%= button_to "Logout", '/logout', method: :post %>
              <% elsif current_user.followees.include?(user) %>
                <h5><%= button_to '<i class="fa-solid fa-user-xmark"></i>  Dejar de Seguir'.html_safe, unfollow_user_path(user), method: "POST" %></h5>
              <% else %>
                <h5><%= button_to '<i class="fa-solid fa-user-plus"></i>  Seguir'.html_safe, follow_user_path(user), method: "POST"  %></h5>
              <% end%>
            </section>
            <a href="<%= user_path(user)%>" class="follow">Ir al Perfil</a>
          </figcaption>
        </figure>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container d-flex">
  <div class="col-3 ">
    <div class="sticky-top" style="z-index: 1">
      <figure class="snip1336">
        <%= cl_image_tag @user.photo.key if @user.photo.attached? %>
        <figcaption>
          <h2><%= @user.first_name %> <%= @user.last_name %><span><%= @user.user_name %></span></h2>
          <p class="metrics-links"><%= @user.gifts.count %> Regalos <%= @user.lists.count %> Listas <%= link_to "#{@user.followers.count} Seguidores", user_followers_path %> <%= link_to "#{@user.followees.count} Seguidos", user_followees_path %></p>
          <p><i class="fa-solid fa-map-location-dot"></i> <%= @user.address %></p>
          <p><i class="fa-solid fa-cake-candles"></i> <%= @user.birth_date %></p>
          <section class="follow-links">
            <% if @user.id == current_user.id %>
                <%= button_to "Logout", '/logout', method: :post %>
            <% elsif current_user.followees.include?(@user) %>
                <h5><%= button_to "Dejar de Seguir", unfollow_user_path(@user), method: "POST" %></h5>
            <% else %>
                <h5><%= button_to "Seguir", follow_user_path(@user), method: "POST"  %></h5>
            <% end%>
          </section>
        </figcaption>
      </figure>
    </div>
  </div>
  <div class="m-4 mb-0 col-9">
    <%= render "shared/gift_order" %>
    <div class="cards">
      <% @gifts.each do |gift| %>
        <%= render "gifts/gift_card", gift: gift %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <p>LISTAS</p>
  <div class="flip-cards-grid">
    <% @lists.where(user_id: @user.id).each do |list| %>
        <%= render 'lists/list_card', list: list %>
    <% end %>
  </div>
</div>


<style>
  .sticky-top {
    top: 80px;
}
</style>