config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :follows

  root to: "pages#home"

  resources :lists, shallow: true do
    resources :gifts
  end

  # LO ANTERIOR, ES LO MISMO QUE DECIR: (Shallow, nestea solo con new y create)
  # resources :lists do
  #   resources :gifts, only: %i[new create]
  # end

  resources :gifts, only: %i[show index edit update destroy] do

    resources :comments, only: %i[create]
  end

  # reservar regalo
  post '/gift/:id/reservar', to: "gifts#reserve", as: "reserve_gift"
  post '/gift/:id/desreservar', to: "gifts#unreserve", as: "unreserve_gift"

  resources :comments, only: %i[update destroy]
  resources :users, only: %i[index show]

  # Followers model
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/followers', to: "users#followers", as: "user_followers"
  get '/users/:id/followees', to: "users#followees", as: "user_followees"

  get '/search', to: "pages#searches", as: "search"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer mt-auto container__footer">

  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>


  </div>
    <div class="footer-copyright">
      <p>Creado con <i class="fas fa-heart"></i> para el mundo</p>
    </div>
</div> %>

<div class="footer mt-auto">
  <div class="container__footer">
    <div class="box__footer">
      <div class="logo">
        <%= image_tag "logos/galo_logo.png" %>
      </div>
    </div>
    <div class="box__footer">
      <h2>Soluciones</h2>
      <a href="https://www.google.com">App Desarrollo</a>
      <a href="#">App Marketing</a>
      <a href="#">IOS Desarrollo</a>
      <a href="#">Android Desarrollo</a>
    </div>

    <div class="box__footer">
      <h2>Compañia</h2>
      <a href="#">Acerca de</a>
      <a href="#">Trabajos</a>
      <a href="#">Procesos</a>
      <a href="#">Servicios</a>
    </div>

    <div class="box__footer">
      <h2>Redes Sociales</h2>
      <a href="#"> <i class="fab fa-facebook"></i> Facebook</a>
      <a href="#"><i class="fab fa-twitter"></i> Twitter</a>
      <a href="#"><i class="fab fa-linkedin"></i> Linkedin</a>
      <a href="#"><i class="fab fa-instagram"></i> Instagram</a>
    </div>

  </div>

  <div class="box__copyright">
      <hr>
      <p>Batch905 - Le Wagon - 2022</p>
  </div>
</div>

app/views/shared/_gift_card.html.erb
<div class="col-3">
  <div class="product-grid p-4">
    <div class="product-image">
        <h3 class="title">
        <%= link_to "#{gift.title}", gift_path(gift)%>
      </h3>
      <p class="text-capitalize"><%= gift.description %></p>
      <div>
        <%= link_to "Ver Mas", gift_path(gift), class:"btn btn-primary text-uppercase" %>
        <div class="price">$ <%= number_with_precision(gift.price, :precision => 0, :delimiter => ',') %></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_gift_order.erb
<ul class="list-group list-group-horizontal justify-content-end my-3">
    <div class="flex-grow text-uppercase m-auto text-uppercase text-bold"> Regalos</div>
    <li class="list-group-item d-flex align-items-center">
      <p class="m-0 small">Precio</p>
      <%= link_to '<i class="fa-solid fa-arrow-up-1-9"></i>'.html_safe, gifts_path(order:"price", user: params[:user]), class: "btn btn-outline-secondary btn-sm m-1" %>
      <%= link_to '<i class="fa-solid fa-arrow-down-9-1"></i>'.html_safe, gifts_path(order:"price", desc: true, user: params[:user]), class: "btn btn-outline-secondary btn-sm" %>
    </li>
    <li class="list-group-item d-flex align-items-center">
      <p class="m-0 small">Fecha Agregado</p>
      <%= link_to '<i class="fa-solid fa-arrow-up-a-z"></i>'.html_safe, gifts_path(order:"created_at", user: params[:user]), class: "btn btn-outline-secondary btn-sm m-1" %>
      <%= link_to '<i class="fa-solid fa-arrow-down-z-a"></i>'.html_safe, gifts_path(order:"created_at", desc: true, user: params[:user]), class: "btn btn-outline-secondary btn-sm" %>
    </li>
    <li class="list-group-item d-flex align-items-center">
      <p class="m-0 small">Título</p>
      <%= link_to '<i class="fa-solid fa-arrow-up-a-z"></i>'.html_safe, gifts_path(order:"title", user: params[:user]), class: "btn btn-outline-secondary btn-sm m-1" %>
      <%= link_to '<i class="fa-solid fa-arrow-down-z-a"></i>'.html_safe, gifts_path(order:"title", desc: true, user: params[:user]), class: "btn btn-outline-secondary btn-sm" %>
    </li>
    <li class="list-group-item d-flex align-items-center">
      <p class="m-0 small">Deseómetro</p>
      <%= link_to '<i class="fa-solid fa-arrow-up-1-9"></i>'.html_safe, gifts_path(order:"ranking", user: params[:user]), class: "btn btn-outline-secondary btn-sm m-1" %>
      <%= link_to '<i class="fa-solid fa-arrow-down-9-1"></i>'.html_safe, gifts_path(order:"ranking", desc: true, user: params[:user]), class: "btn btn-outline-secondary btn-sm" %>
    </li>
  </ul>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon fixed-top"
  data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logos/galo_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="search-input">
          <%= form_with url: search_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Busca usuarios o regalos"
            %>
            <%= button_tag(type: "submit", class: "btn btn-outline-success") do %>
                <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          <% end %>
        </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Explorar Listas", lists_path(), class: "nav-link raise up" %>
        </li>
        <li class="nav-item">
          <%= link_to "Explorar regalos", gifts_path, class: "nav-link raise up" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Agregar Regalo", new_list_gift_path(List.find_by_user_id(current_user), @gift), class: "nav-link raise up" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mis Amigos", user_followees_path(current_user), class: "nav-link raise up" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%=  image_tag "random-user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Mis Listas", lists_path(user: current_user), class: "dropdown-item" %>
              <%= link_to "Mis Regalos", gifts_path(user: current_user), class: "dropdown-item" %>
              <%= link_to "Editar usuario", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Desloguearme", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar/Registrarse", new_user_session_path, class: "nav-link raise up" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_comment.html.erb
<%= simple_form_for [gift, comment] do |f| %>
    <%= f.input :content, placeholder:"Ingresa tu comentario", label: false %>
    <%= f.button :submit, "Enviar", class: "btn btn-primary" %>
<% end %>