config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :follows

  root to: "pages#home"

  resources :lists, shallow: true do
    resources :gifts
  end

  # LO ANTERIOR, ES LO MISMO QUE DECIR: (Shallow, nestea solo con new y create)
  # resources :lists do
  #   resources :gifts, only: %i[new create]
  # end

  resources :gifts, only: %i[show index edit update destroy] do

    resources :comments, only: %i[create]
  end

  # reservar regalo
  post '/gift/:id/reservar', to: "gifts#reserve", as: "reserve_gift"
  post '/gift/:id/desreservar', to: "gifts#unreserve", as: "unreserve_gift"

  resources :comments, only: %i[update destroy]
  resources :users, only: %i[index show]

  # Followers model
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/followers', to: "users#followers", as: "user_followers"
  get '/users/:id/followees', to: "users#followees", as: "user_followees"

  get '/search', to: "pages#searches", as: "search"

end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one_attached :photo
  belongs_to :list
  has_many :comments, dependent: :destroy

  validates :url, :title, presence: true
  validates :title, length: { maximum: 50 }
  validates :description, length: { maximum: 280 }

  include PgSearch::Model
  multisearchable against: %i[title price description]
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_gift, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @gifts = policy_scope(Gift)
    if params[:order].in? %w[price title created_at ranking]
      @gifts = @gifts.order("gifts.#{params[:order]} #{params[:desc] ? 'DESC' : ''}")
    else
      @gifts = policy_scope(Gift)
    end
  end

  def new
    @gift = Gift.new
    authorize @gift
  end

  def create
    @gift = Gift.new(gift_params)
    if @gift.save
      redirect_to list_path(@gift.list_id)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @gift
  end

  def show
    @comment = Comment.new
    authorize @gift
  end

  def edit
    authorize @gift
  end

  def update
    if @gift.update(gift_params)
      redirect_to gift_path(@gift)
    else
      render :edit, status: :unprocessable_entity
    end
    authorize @gift
  end

  def destroy
    @gift.destroy
    redirect_to list_path(@gift.list_id), status: :see_other
    authorize @gift
  end

  def reserve
    @gift = Gift.find(params[:id])
    @gift.status = "pendiente"
    @gift.save
    authorize @gift
  end

  def unreserve
    @gift = Gift.find(params[:id])
    @gift.status = "disponible"
    @gift.save
    authorize @gift
  end


  private

  def set_gift
    @gift = Gift.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def gift_params
    params.require(:gift).permit(:url, :title, :gift_picture, :price, :ranking, :description, :status, :photo, :list_id)
  end
end

app/views/gifts/_gift_card.html.erb
<div class="col-12">
  <div class="card-gift">
    <div class="">
    <%= '<span class="new-gift-badge badge bg-success small">new</span>'.html_safe if gift.created_at >= (Date.today -7)  %>
      <div class="gift-img-container" >
        <% if gift.photo.key == nil%>
          <%= image_tag "random-gift.jpg" %>
        <% else %>
          <%= cl_image_tag gift.photo.key %>
        <% end %>
      </div>
      <p class=" gift-price">$ <%= number_with_precision(gift.price, :precision => 0, :delimiter => ',') %></p>
      <h2 class="">
        <%= link_to "#{gift.title}", gift_path(gift), data: { turbo_frame: "modal" }%>
      </h2>
      <ul class="card_stars">
        <%='<li><i class="fa-solid fa-heart red"></i></li>'.html_safe *  gift.ranking %><%='<li><i class="fa-regular fa-heart"></i></li>'.html_safe *  (5 - gift.ranking) %>
      </ul>
      <p class="gift-info text-capitalize">
      <% if gift.description?%>
        <% if gift.description.length > 40 %>
          <%= truncate(gift.description, length: 40) %>
        <%= link_to '...Leer más', gift_path(gift.id), data: { turbo_frame: "modal" } %>
        <% else %>
          <%= gift.description %>
        <% end %> </p>
      <% else %>
        "Sin detalle"
      <% end %> </p>

      <div class="gift-bottom">
        <%= link_to "Ver Más", gift_path(gift.id), class: "btn btn-primary", data: { turbo_frame: "modal" } %>
      </div>
    </div>
  </div>
</div>

app/views/gifts/_gift_new_form.html.erb
<div>
  <%= simple_form_for [@list, @gift], html: { class: "d-flex justify-content-between form-gift align-items-center flex-column"} do |f| %>
    <%= f.association :list, label: "Lista", selected: @list.id, include_blank: false, collection: List.where(user_id: current_user), wrapper_html: { class: 'form-control form-gift-item' }  %>
      <%= f.input :url, placeholder:"URL del Producto", label: false, wrapper_html: { class: 'form-control form-gift-item' }  %>
    <%= f.input :title, placeholder:"Titulo", label: false, wrapper_html: { class: 'form-control form-gift-item' } %>
    <%= f.input :description, placeholder:"Descripcion del Regalo", label: false, wrapper_html: { class: 'form-control form-gift-item' }  %>
    <div class="row">
      <div class="col-6">
        <%= f.input :price, as: :currency, label: "Precio", wrapper_html: { class: 'form-gift-item px-1 form-clean' } %>
      </div>
      <div class="col-6">
        <%= f.input :ranking, as: :select, collection: 1..5, selected: 1, include_blank: false, label: "Deseómetro", wrapper_html: { class: 'form-gift-item px-1 form-clean' } %>
      </div>
    </div>
    <%= f.input :photo, label: "Foto del Regalo", as: :file, wrapper_html: { class: 'form-control form-gift-item' }  %>
    <%= f.submit "Agrega tu Regalo", class: "btn btn-primary my-3" %>
  <% end %>
</div>

app/views/gifts/_gift_show.html.erb
<div class="">
  <div class="gift_show">
    <div class="card-show">
      <div class="card__title">
        <div class="icon">
          <a href="<% gifts_path %>"><i class="fa fa-arrow-left"></i></a>
        </div>
        <%= image_tag "logos/galo_logo.png", style: "width: 50px; height: 50px; margin-left:50px;" %>
      </div>
      <div class="card__body">
        <div class="half">
          <div class="featured_text">
            <h1><%= @gift.title %></h1>
            <p class="price">$ <%= @gift.price %></p>
          </div>
          <div class="image">
            <% if @gift.photo.key == nil%>
              <%= image_tag "random-gift.jpg", crop: :fill %>
            <% else %>
              <%= cl_image_tag @gift.photo.key, crop: :fill %>
            <% end %>
          </div>
        </div>
        <div class="half">
          <div class="description">
            <p><%= @gift.description %></p>
          </div>
          <p>ESTADO: <%= @gift.status == "disponible" ? "El regalo no ha sido reservado por nadie" : "El regalo fue reservado" %> </p>
          <section class="reserve-links">
            <% if @gift.status == "pendiente" %>
                <h5><%= button_to "Cancelar Reserva", unreserve_gift_path, method: "POST", class:"btn btn-secondary btn-sm"  %></h5>
            <% else %>
                <h5><%= button_to "Reservar", reserve_gift_path, method: "POST", class:"btn btn-secondary btn-sm"  %></h5>
            <% end %>
          </section>
          <div class="reviews d-flex">
            <p>Deseometro:   </p>
            <ul class="stars">
              <%='<li><i class="fa-solid fa-heart"></i></li>'.html_safe *  @gift.ranking %><%='<li><i class="fa-regular fa-heart"></i></li>'.html_safe *  (5 - @gift.ranking) %>
            </ul>
          </div>
          <div class="user-edit">
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, gift_path(@gift), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"}  if policy(@gift).destroy? %>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_gift_path(@gift), class:"btn btn-primary" if policy(@gift).edit? %>
          </div>
          <div class="comments">
            <% @gift.comments.each do |comment| %>
              <div class="card mt-2">
                <div class="card-header">
                  <%= comment.user.user_name %> comentó:
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <p class="text-sm"><%= comment.content %></p>
                    <footer class="blockquote-footer">Publicado el <cite title="Source Title"><%= comment.created_at %></cite>
                    <% if comment.user == current_user %>
                      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, comment_path(comment.id), class:"btn btn-danger btn-sm mx-3", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} %>
                    <% end %>
                    </footer>
                  </blockquote>
                </div>
              </div>
            <% end %>
            <%= render "shared/new_comment", gift: @gift, comment: @comment %>
          </div>
        </div>
      </div>
      <div class="card__footer">
        <div class="recommend">
          <p><%= @gift.list.title %></p>
          <h3>by <a href="<%= user_path(@gift.list.user)%>"><%= @gift.list.user.user_name %></a></h3>
        </div>
        <div class="action">
          <a href="<%= @gift.url %>" class="btn btn-primary text-uppercase" target="_blank"><i class="fa-solid fa-cart-shopping"></i>  Ir a la tienda </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gifts/_search_gift.html.erb
<div class="col-12">
  <div class="card-gift">
    <div class="">
    <%= '<span class="new-gift-badge badge bg-success small">new</span>'.html_safe if element.searchable.created_at >= (Date.today -7)  %>
      <div class="gift-img-container" >
        <% if element.searchable.photo.key == nil%>
          <%= image_tag "random-gift.jpg" %>
        <% else %>
          <%= cl_image_tag element.searchable.photo.key %>
        <% end %>
      </div>
      <p class=" gift-price">$ <%= number_with_precision(element.searchable.price, :precision => 0, :delimiter => ',') %></p>
      <h2 class="">
        <%= link_to "#{element.searchable.title}", gift_path(element), data: { turbo_frame: "modal" }%>
      </h2>
      <p class="gift-info text-capitalize">
      <% if element.searchable.description?%>
        <% if element.searchable.description.length > 40 %>
          <%= truncate(element.searchable.description, length: 40) %>
        <%= link_to '...Leer más', gift_path(element.searchable.id), data: { turbo_frame: "modal" } %>
        <% else %>
          <%= element.searchable.description %>
        <% end %> </p>
      <% else %>
        "Sin detalle"
      <% end %> </p>

      <div class="gift-bottom">
        <%= link_to "Ver Mas", gift_path(element.searchable.id), class: "btn btn-primary", data: { turbo_frame: "modal" } %>
      </div>
    </div>
  </div>
</div>

app/views/gifts/_show.html.erb
<h1>ReGALO</h1>

<div class="container">
  <div>
    <div class="row">
      <div class="col-6">
        <% if @gift.photo.key == nil%>
        <% else %>
          <%= cl_image_tag @gift.photo.key, style: "width:100%; height:500px;", crop: :fill %>
        <% end %>
      </div>
      <div class="col-6 bg-dark text-white" style="height:500px;">
        <h2><%= @gift.title %></h2>
        <a href="<%= @gift.url %>">Ir al Sitio</a>
        <p>PRECIO: $<%= @gift.price %></p>
        <p>CUANTO LO QUIERO: <%= @gift.ranking %></p>
        <p>DESCRIPCIÓN: <%= @gift.description %></p>
        <p>ESTADO: <%= @gift.status %></p>
        <p>Pertenece a la Lista: <%= @gift.list.title %></p>
        <%= link_to '<i class="fa fa-trash"></i>'.html_safe,   gift_path(@gift), class:"btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} %>
      </div>
    </div>
  </div>

  <% @gift.comments.each do |comment| %>
    <div class="card mt-2">
      <div class="card-header">
        <%= comment.user.user_name %> dice:
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= comment.content %></p>
          <footer class="blockquote-footer">Publicado el <cite title="Source Title"><%= comment.created_at %></cite></footer>
          <% if comment.user == current_user %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, comment_path, class:"btn btn-warning", data: {turbo_method: :delete, turbo_confirm: "Seguro?"} %>
          <% end %>
        </blockquote>
      </div>
    </div>
  <% end %>

  <%= render "shared/new_comment", gift: @gift, comment: @comment %>
</div>

app/views/gifts/create.turbo_stream.erb
<%= turbo_stream.prepend "gifts", @gift %>

app/views/gifts/edit.html.erb
<div class="container my-3" >
    <div class="my-3 gift-edit-container">
      <%= simple_form_for @gift do |f| %>
        <div class="row" >
          <div class="col-6 d-flex align-items-center flex-column justify-content-around px-5 fondo" >
            <div class="foto d-flex flex-column align-items-center pt-4" data-aos="fade-up" data-aos-duration="3000">
              <%= cl_image_tag @gift.photo.key  %>
            </div>
          </div>
          <div class= "col-6 px-5">
            <h2 class="text-uppercase mb-4 text-center pt-4"><%= @gift.title%></h2>
            <div class=" pt-3">
              <%= f.input :url, label: "Ingresar la Dirección web", wrapper_html: { class: "" }%>
              <%= f.input :title, label: "Titulo", wrapper_html: { class: '' } %>
              <%= f.input :description, label: "Descripción", wrapper_html: { class: '' }  %>

              <%= f.input :photo, label: "Foto", as: :file %>
              <div class="row">
                <div class="col-lg-6">
                  <%= f.input :ranking, label: "Puntuacion" %>
                </div>
                <div class="col-lg-6">
                  <%= f.input :price, label: "Precio $", wrapper_html: { class: '' } %>
                </div>
              </div>
            </div>

            <div class="form-actions d-flex flex-column align-items-center justify-content-around">
              <%= f.button :submit, "Editar Regalo", class: " btn btn-primary" %>
              <%= link_to "Volver", :back %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/gifts/index.html.erb
<%# PARA HACER EL GRID, SE HACE POR ARRIBA DE LA ITERACIÓN %>
<div class="container">
  <%= render "shared/gift_order" %>
  <div class="cards my-3">
      <% if params[:user].present? %>
        <% @gifts.includes(:list).where('lists.user_id = ?', params[:user]).references(:lists).each do |gift| %>
          <%= render "gift_card", gift: gift %>
        <% end %>
      <% else %>
        <% @gifts.includes(:list).where('lists.privacy = ?', 'pública').references(:lists).each do |gift| %>
          <%= render "gift_card", gift: gift %>
        <% end %>
      <% end %>
  </div>
</div>

app/views/gifts/new.html.erb
<div class="container container-form-new-gift">
  <div class="row">
    <div class="col-6 d-flex align-items-center flex-column justify-content-around">
      <div class="flexbox rotate-scale-up">
        <%= image_tag "logos/galo_logo.png" %>
      </div>
    </div>
    <div class="col-6 fondo">
      <div class="gift-new-container">
        <h2>Agregá un regalo</h2>
        <%= render 'gift_new_form' %>
      </div>
    </div>
  </div>
</div>

app/views/gifts/show.html.erb
<main class="container">
  <%= turbo_frame_tag "modal" do %>
    <div class="modal-body">
      <%= render "gifts/gift_show", gift: @gift %>
    </div>
  <% end %>
</main>